-- MySQL Script generated by MySQL Workbench
-- Wed May 15 15:25:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Cinema` DEFAULT CHARACTER SET utf8 ;
USE `db_Cinema` ;

-- -----------------------------------------------------
-- Table `db_Cinema`.`tbl_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Cinema`.`tbl_roles` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Cinema`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Cinema`.`tbl_users` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(500) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `salt` VARCHAR(32) NOT NULL,
  `role_id` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_users_tbl_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_tbl_users_tbl_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_Cinema`.`tbl_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Cinema`.`tbl_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Cinema`.`tbl_permissions` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `access` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Cinema`.`tbl_user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Cinema`.`tbl_user_details` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `name` VARCHAR(500) NOT NULL,
  `surname` VARCHAR(500) NOT NULL,
  INDEX `fk_tbl_user_details_tbl_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_user_details_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_Cinema`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Cinema`.`tbl_login_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Cinema`.`tbl_login_sessions` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `expiration` INT(11) NOT NULL,
  `sess_identifier` VARCHAR(100) NOT NULL,
  INDEX `fk_tbl_login_sessions_tbl_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_login_sessions_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_Cinema`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Cinema`.`tbl_login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Cinema`.`tbl_login_attempts` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `attempts` TINYINT(1) NOT NULL,
  `ip_address` VARCHAR(50) NOT NULL,
  `lock` INT(11) NULL,
  `user_id` MEDIUMINT(8) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_login_attempts_tbl_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_login_attempts_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_Cinema`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_Cinema`.`tbl_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_Cinema`;
INSERT INTO `db_Cinema`.`tbl_roles` (`id`, `name`) VALUES (1, 'Administrator');
INSERT INTO `db_Cinema`.`tbl_roles` (`id`, `name`) VALUES (2, 'Editor');
INSERT INTO `db_Cinema`.`tbl_roles` (`id`, `name`) VALUES (4, 'Subscriber');
INSERT INTO `db_Cinema`.`tbl_roles` (`id`, `name`) VALUES (8, 'Guest');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_Cinema`.`tbl_permissions`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_Cinema`;
INSERT INTO `db_Cinema`.`tbl_permissions` (`id`, `name`, `access`) VALUES (DEFAULT, 'BACKEND_ACCESS', 3);
INSERT INTO `db_Cinema`.`tbl_permissions` (`id`, `name`, `access`) VALUES (DEFAULT, 'ADD_USERS', 1);

COMMIT;
